import { parseLevels, type Level } from '../engine/index.ts';
import cardium from './cardium.json' with { type: 'json' };
import montney from './montney.json' with { type: 'json' };

export interface Region {
  id: string;
  name: string;
  blurb: string;
  levels: Level[];
}

// Level files are generated by `npm run gen-levels`. Don't edit them by hand.
export const REGIONS: Region[] = [
  { id: 'cardium', name: 'Cardium', blurb: 'Trucks and gates. Learn the lease.', levels: parseLevels(cardium) },
  { id: 'montney', name: 'Montney', blurb: 'Pumpjacks, tanks and wellheads never move. Plan around them.', levels: parseLevels(montney) },
];
